name: 'Run CI jobs'

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 5'  # 18:00 on Friday JST

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: 'Configure dependencies'
        run: |
          uv sync --all-extras --frozen
      - name: 'Run linters'
        run: |
          lefthook run pre-commit --all-files
  source-test:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version:
          {%- if cookiecutter.requires_python in ["3.9"] %}
          - '3.9'
          {%- endif %}
          {%- if cookiecutter.requires_python in ["3.9", "3.10"] %}
          - '3.10'
          {%- endif %}
          {%- if cookiecutter.requires_python in ["3.9", "3.10", "3.11"] %}
          - '3.11'
          {%- endif %}
          {%- if cookiecutter.requires_python in ["3.9", "3.10", "3.11", "3.12"] %}
          - '3.12'
          {%- endif %}
          {%- if cookiecutter.requires_python in ["3.9", "3.10", "3.11", "3.12", "3.13"] %}
          - '3.13'
          {%- endif %}
        workspace: ['locked', 'latest']
    steps:
      - uses: actions/checkout@v3
      - uses: jdx/mise-action@v2
      {%- raw %}
      - name: 'Stand by python-version'
        run: |
          echo ${{ matrix.python-version }} > .python-version
      - name: 'Configure env as locked deps by uv.lock'
        run: |
          uv sync --all-extras --frozen
        if: ${{ matrix.workspace == 'locked'}}
      - name: 'Configure env as latest deps on PyPI'
        run: |
          uv sync --all-extras --upgrade
        if: ${{ matrix.workspace == 'latest'}}
      {%- endraw %}
      - name: 'Run tests'
        run: |
          uv run pytest
  docs-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: 'Configure dependencies'
        run: |
          uv sync --all-extras --frozen
      - name: 'Run tests'
        run: |
          task setup docs:build-linkcheck docs:build-dirhtml
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: 'Try building as package'
        run: |
          uv build
          ls -l dist
