name: 'Release new version'

on:
  push:
    tags:
      - 'v*.*.*'

env:
  UV_NO_SYNC: 1
  TASK_X_REMOTE_TASKFILES: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: aquaproj/aqua-installer@9ebf656952a20c45a5d66606f083ff34f58b8ce0 # v4.0.0
        with:
          aqua_version: v2.43.1
      - name: 'Build package'
        run: |
          uv build
      {%- raw %}
      - uses: actions/upload-artifact@v4
        with:
          name: packages-${{ github.ref_name }}
          path: dist/
      {%- endraw %}
  gh-release:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      {%- raw %}
      - uses: actions/download-artifact@v4
        with:
          name: packages-${{ github.ref_name }}
          path: dist/
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'dist/*'
          bodyFile: '.github/release-body.md'
          draft: false
          name: Release ${{ github.ref_name }}
          tag: ${{ github.ref }}
          prerelease: false
      {%- endraw %}
  publish-pypi:
    needs: [build]
    runs-on: ubuntu-latest
    {%- raw %}
    if: success() && ${{ needs.prepare.outputs.is-release }}
    {%- endraw %}
    environment:
      name: 'pypi'
      url: 'https://pypi.org/p/{{ cookiecutter.project_name }}'
    permissions:
      id-token: write
    steps:
      {%- raw %}
      - uses: actions/download-artifact@v4
        with:
          name: packages-${{ github.ref_name }}
          path: dist/
      {%- endraw %}
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
  deploy-docs:
    needs: [build]
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    {%- raw %}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    {%- endraw %}
    steps:
      - uses: actions/checkout@v5
      - uses: aquaproj/aqua-installer@9ebf656952a20c45a5d66606f083ff34f58b8ce0 # v4.0.0
        with:
          aqua_version: v2.43.1
      - name: Build document
        run: |
          task --yes setup docs:build-mini18n-dirhtml
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/_build/mini18n-dirhtml
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
