current_version = "{{ cookiecutter.version }}"

[[files]]
path = "pyproject.toml"
{% raw %}
search = "version = \"{{current_version}}\""
replace = "version = \"{{new_version}}\""
{% endraw %}

[[files]]
path = "src/atsphinx/{{cookiecutter.package_basename}}/__init__.py"
{% raw %}
search = "version = \"{{current_version}}\""
replace = "version = \"{{new_version}}\""
{% endraw %}

[[files]]
path = "CHANGES.rst"
{% raw %}
search = """
v{{current_version}}
={% for _ in current_version %}={% endfor %}
"""
replace = """
v{{new_version}}
={% for _ in new_version %}={% endfor %}

:Date: {{ now|date }} (Asia/Tokyo)

Breaking changes
----------------

Features
--------

Fixes
-----

Others
------

v{{current_version}}
={% for _ in current_version %}={% endfor %}
"""
{% endraw %}

[[files]]
path = ".github/release-body.md"
search = "Release {{ cookiecutter.project_name }} v{{ '{{ current_version }}' }}"
replace = "Release {{ cookiecutter.project_name }} v{{ '{{ new_version }}' }}"

[[files]]
path = ".github/release-body.md"
search = "- Changelog is https://github.com/atsphinx/{{ cookiecutter.project_basename }}/blob/v{{ '{{ current_version }}' }}/CHANGES.rst"
replace = "- Changelog is https://github.com/atsphinx/{{ cookiecutter.project_basename }}/blob/v{{ '{{ new_version }}' }}/CHANGES.rst"
