#!/bin/sh

# Setup as git repository
git init
lefthook install

# Initialize and verify workspace
uv sync --all-extras
task docs:intl
task verify

# Save
git add .
git commit -m "Initial commit

- Generated by cookiecutter
- Used https://github.com/atsphinx/cookiecutter-sphinx-extension
"
