#!/bin/sh

# Setup as git repository
git init --initial-branch=main .

# Configure CLI
aqua i

# Initialize and verify workspace
cp .env.example .env
uv sync --all-extras --all-groups
task --yes setup
task --yes docs:intl
task --yes verify

# Save
git add .
git commit -m "Initial commit

- Generated by cookiecutter
- Used https://github.com/atsphinx/cookiecutter-sphinx-extension
"

# 
git switch -c dev
