name: Continuous Integration

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  cookiecutter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          architecture: x64
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: pip install cookiecutter pre-commit
      - name: Create demo project
        run: |
          cookiecutter --no-input --output-dir=var .
          python -m venv var/venv
          source var/venv/bin/activate
          cd var/demo
          git init
          pip install '.[test]'
          pytest
          make -C docs dirhtml
          pre-commit run --all-files
