name: Continuous Integration

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  cookiecutter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          architecture: x64
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies 
        run: pip install uv cookiecutter pre-commit
      - name: Create demo project
        run: |
          cookiecutter --no-input --output-dir=var .
      - name: Verify created project
        run: |
          cd var/demo
          git init
          git add .
          uv sync
          uv run pytest
          uv run make -C doc dirhtml
          pre-commit run --all-files
