name: Continuous Integration

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  cookiecutter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v5
      - uses: aquaproj/aqua-installer@9ebf656952a20c45a5d66606f083ff34f58b8ce0 # v4.0.0
        with:
          aqua_version: v2.43.1
      - name: 'Create demo project'
        run: |
          git config --global user.email "user@example.com"
          git config --global user.name "Test user"
          uvx cookiecutter --no-input --output-dir=var .
      - name: Verify created project
        run: |
          cd var/demo
          rm -rf .venv
          uv sync --python='${{ steps.setup-python.outputs.python-path }}'
          task verify
