name: Continuous Integration

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  cookiecutter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v2
      - uses: arduino/setup-task@v2
      - name: Create demo project
        run: |
          uvx cookiecutter --no-input --output-dir=var .
      - uses: actions/setup-python@v5
        id: 'setup-python'
        with:
          architecture: x64
          python-version: ${{ matrix.python-version }}
      - name: Verify created project
        run: |
          cd var/demo
          git init
          uv sync --python='${{ steps.setup-python.outputs.python-path }}'
          task verify
